#!/usr/bin/env python3
"""
Local tangent-plane (kNN + PCA + 2D Delaunay) triangulator for point clouds.

Goal
----
When you reconstruct a surface from a point cloud (e.g., inside a CVT remeshing
pipeline), 3D Delaunay/convex-hull surface extraction can create long, wrong
triangles that "reach across" thin parts. This script instead builds triangles
*locally* by:

  1) kNN neighborhood per point
  2) PCA to estimate tangent plane basis (u,v) at the point
  3) Project neighbors to 2D (tangent plane coords)
  4) 2D Delaunay triangulation
  5) Keep only triangles incident to the center point
  6) Filter triangles with overly long edges to avoid far connections
  7) Merge all local triangles and deduplicate

Input
-----
- A single .txt file OR a directory containing multiple .txt files.
- Each .txt: xyz per line. Lines may contain comments starting with '#'.

Output
------
- By default: preview/visualize only (no saving).
- With --write: writes an .obj for each .txt (same basename) into --out_dir
  (or next to input if --out_dir omitted).

Dependencies
------------
pip install numpy scipy
Optional for nicer preview:
pip install pyvista

Examples
--------
Preview one file:
  python see_mesh.py input.txt --k 24 --preview

Batch convert a directory (will preview first, then write):
  python see_mesh.py ./points_dir --k 24 --preview_first --write --out_dir ./obj_out
"""

from __future__ import annotations

import argparse
import os
from dataclasses import dataclass
from typing import List, Optional, Set, Tuple

import numpy as np
from scipy.spatial import cKDTree, Delaunay


# ----------------------------
# IO
# ----------------------------

def load_xyz_txt(path: str) -> np.ndarray:
    pts = []
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "#" in line:
                line = line.split("#", 1)[0].strip()
            if not line:
                continue
            parts = line.replace(",", " ").split()
            if len(parts) < 3:
                continue
            try:
                x, y, z = map(float, parts[:3])
                pts.append((x, y, z))
            except ValueError:
                continue
    P = np.asarray(pts, dtype=np.float64)
    if P.ndim != 2 or P.shape[1] != 3:
        raise ValueError(f"Bad point data in {path}")
    return P


def write_obj(path: str, P: np.ndarray, F: np.ndarray) -> None:
    os.makedirs(os.path.dirname(path) or ".", exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("# generated by see_mesh.py (local tangent-plane triangulator)\n")
        for v in P:
            f.write(f"v {v[0]:.9g} {v[1]:.9g} {v[2]:.9g}\n")
        for tri in F:
            # OBJ is 1-based
            a, b, c = tri.astype(int) + 1
            f.write(f"f {a} {b} {c}\n")


# ----------------------------
# Geometry core
# ----------------------------

@dataclass
class TriangulateParams:
    k: int = 24
    edge_max_factor: float = 2.5
    # If your points are noisy, increasing helps stability:
    min_neighbors_for_pca: int = 8
    # Limit how many triangles one center contributes (prevents huge fan explosions)
    max_tris_per_center: int = 64


def _tangent_basis_pca(X: np.ndarray) -> Optional[np.ndarray]:
    """
    X: (m,3) neighbors in *centered* coordinates (center at origin), excluding center itself.
    Returns basis B (3,2) columns are u,v tangent axes.
    """
    if X.shape[0] < 3:
        return None
    # covariance in 3D
    C = (X.T @ X) / max(1, X.shape[0])
    # eigh for symmetric matrix; eigenvalues ascending
    w, V = np.linalg.eigh(C)
    # smallest eigenvector ~ normal; tangent plane spans the other two
    # V columns are eigenvectors
    u = V[:, 1]
    v = V[:, 2]
    B = np.stack([u, v], axis=1)  # (3,2)
    return B


def triangulate_local_tangent(P: np.ndarray, params: TriangulateParams) -> np.ndarray:
    """
    Returns faces F as (t,3) int indices into P.
    """
    n = int(P.shape[0])
    if n < 3:
        return np.zeros((0, 3), dtype=np.int32)

    k = int(params.k)
    k = max(6, k)

    tree = cKDTree(P)

    faces: List[Tuple[int, int, int]] = []
    seen: Set[Tuple[int, int, int]] = set()

    for i in range(n):
        # k+1 includes self
        kk = min(k + 1, n)
        dists, idxs = tree.query(P[i], k=kk)
        idxs = np.asarray(idxs, dtype=np.int64).reshape(-1)
        dists = np.asarray(dists, dtype=np.float64).reshape(-1)

        # Ensure center i is present at position 0
        if idxs[0] != i:
            # Insert self manually (rare if duplicates)
            idxs = np.concatenate(([i], idxs))
            dists = np.concatenate(([0.0], dists))

        # We need enough neighbors for PCA stability
        if idxs.shape[0] - 1 < params.min_neighbors_for_pca:
            continue

        local_to_global = idxs
        X = P[local_to_global] - P[i]  # (m,3), center is row 0 ~ (0,0,0)
        Xn = X[1:, :]                  # exclude center for PCA
        B = _tangent_basis_pca(Xn)
        if B is None:
            continue

        # 2D projection (m,2)
        UV = X @ B

        # 2D Delaunay on neighborhood
        try:
            tri2d = Delaunay(UV)
        except Exception:
            continue

        # Typical local spacing (exclude center): use median kNN distance
        d_med = float(np.median(dists[1:])) if dists.shape[0] > 2 else float(dists[-1])
        edge_max = params.edge_max_factor * max(d_med, 1e-12)

        # Keep only triangles incident to local vertex 0 (the center)
        count_added = 0
        for simp in tri2d.simplices:
            simp = np.asarray(simp, dtype=np.int64)
            if 0 not in simp:
                continue

            g = tuple(int(local_to_global[j]) for j in simp)
            a, b, c = g

            # quick edge-length filter in 3D
            pa, pb, pc = P[a], P[b], P[c]
            lab = np.linalg.norm(pa - pb)
            lbc = np.linalg.norm(pb - pc)
            lca = np.linalg.norm(pc - pa)
            if (lab > edge_max) or (lbc > edge_max) or (lca > edge_max):
                continue

            key = tuple(sorted((a, b, c)))
            if key in seen:
                continue

            seen.add(key)
            faces.append((a, b, c))
            count_added += 1
            if count_added >= params.max_tris_per_center:
                break

    if not faces:
        return np.zeros((0, 3), dtype=np.int32)

    return np.asarray(faces, dtype=np.int32)


# ----------------------------
# Visualization
# ----------------------------

def preview_mesh(P: np.ndarray, F: np.ndarray, title: str = "Preview") -> None:
    """
    Tries PyVista first (interactive), falls back to Matplotlib.
    """
    # PyVista
    try:
        import pyvista as pv

        # PyVista expects faces as [3, i, j, k, 3, ...]
        faces_pv = np.hstack([np.full((F.shape[0], 1), 3, dtype=np.int64), F.astype(np.int64)])
        mesh = pv.PolyData(P, faces_pv)

        pl = pv.Plotter()
        pl.add_text(title, font_size=12)
        pl.add_mesh(mesh, show_edges=True, opacity=1.0)
        pl.add_points(P, render_points_as_spheres=True, point_size=4)
        pl.show()
        return
    except Exception:
        pass

    # Matplotlib fallback
    import matplotlib.pyplot as plt
    from mpl_toolkits.mplot3d.art3d import Poly3DCollection

    fig = plt.figure()
    ax = fig.add_subplot(111, projection="3d")
    ax.set_title(title)

    if F.shape[0] > 0:
        tris = [P[tri] for tri in F]
        poly = Poly3DCollection(tris, alpha=0.85, linewidths=0.2)
        ax.add_collection3d(poly)

    ax.scatter(P[:, 0], P[:, 1], P[:, 2], s=3)

    # autoscale
    mins = P.min(axis=0)
    maxs = P.max(axis=0)
    ctr = (mins + maxs) * 0.5
    span = (maxs - mins).max()
    span = max(span, 1e-9)
    ax.set_xlim(ctr[0] - span / 2, ctr[0] + span / 2)
    ax.set_ylim(ctr[1] - span / 2, ctr[1] + span / 2)
    ax.set_zlim(ctr[2] - span / 2, ctr[2] + span / 2)

    plt.show()


# ----------------------------
# CLI
# ----------------------------

def iter_txt_files(path: str) -> List[str]:
    if os.path.isdir(path):
        out = []
        for name in sorted(os.listdir(path)):
            if name.lower().endswith(".txt"):
                out.append(os.path.join(path, name))
        return out
    else:
        return [path]


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("input", help="A .txt file OR a directory of .txt files")
    ap.add_argument("--k", type=int, default=24, help="kNN size (default: 24)")
    ap.add_argument("--edge_max_factor", type=float, default=2.5,
                    help="Reject triangles with any edge > factor * median(kNN distance) (default: 2.5)")
    ap.add_argument("--min_neighbors_for_pca", type=int, default=8,
                    help="Minimum neighbors (excluding center) to run PCA (default: 8)")
    ap.add_argument("--max_tris_per_center", type=int, default=64,
                    help="Cap triangles contributed by each center point (default: 64)")

    ap.add_argument("--preview", action="store_true",
                    help="Preview each generated mesh (may be slow for many files)")
    ap.add_argument("--preview_first", action="store_true",
                    help="Preview only the first file (useful for batch runs)")

    ap.add_argument("--write", action="store_true",
                    help="Write .obj outputs (default: off; preview-only)")
    ap.add_argument("--out_dir", default=None,
                    help="Output directory for .obj files (default: alongside input .txt)")

    args = ap.parse_args()

    params = TriangulateParams(
        k=args.k,
        edge_max_factor=args.edge_max_factor,
        min_neighbors_for_pca=args.min_neighbors_for_pca,
        max_tris_per_center=args.max_tris_per_center,
    )

    txt_files = iter_txt_files(args.input)
    if not txt_files:
        raise SystemExit("No .txt files found.")

    did_preview_first = False

    for txt in txt_files:
        P = load_xyz_txt(txt)
        F = triangulate_local_tangent(P, params)

        base = os.path.splitext(os.path.basename(txt))[0]
        title = f"{base}: {P.shape[0]} pts, {F.shape[0]} tris (k={params.k})"

        if args.preview or (args.preview_first and not did_preview_first):
            preview_mesh(P, F, title=title)
            did_preview_first = True

        if args.write:
            out_dir = args.out_dir if args.out_dir is not None else os.path.dirname(txt)
            out_path = os.path.join(out_dir, base + ".obj")
            write_obj(out_path, P, F)
            print(f"Wrote: {out_path}   (tris={F.shape[0]})")
        else:
            # Preview-only mode: still print stats for batch runs
            print(f"{txt}: pts={P.shape[0]}  tris={F.shape[0]}")

if __name__ == "__main__":
    main()
